spring:
  datasource:
    url: jdbc:mysql://localhost:3306/friend
    username: root
    password: holeejh0426^
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
    open-in-view: false
univCert:
  key: 1ae13bff-4cb3-46ec-85a0-b38a7f8cfc57
app:
  firebase-bucket: friend-327a9.appspot.com